name: bookkart_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 5.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  nb_utils: ^7.0.4
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1

  # FIREBASE
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_remote_config: ^5.1.3
  epubx: ^4.0.0


  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # NOTIFICATION
  # Firebase Notification
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.3

  lottie: ^3.1.2
  flutter_html: ^3.0.0-beta.2

  # DATABASE
  sqflite: ^2.4.0

  # PATH LIBRARY
  path_provider: ^2.1.4

  # NETWORKING
  http: ^1.2.2

  # DOWNLOAD
  internet_file: ^1.2.0

  # FOR ADS
  google_mobile_ads: ^5.2.0

  # AUTHENTICATION
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.2.1

  # BOOK
  flutter_pdfview: ^1.3.3

  #AUDIO
  just_audio: ^0.9.41

  # VIDEO
  chewie: ^1.8.5
  video_player: ^2.9.2

  # PERMISSION HANDLING
  permission_handler: ^11.3.1


  # UTILITIES
  country_picker: ^2.0.26
  flutter_custom_tabs: ^2.1.0
  speech_to_text: ^7.0.0
  aes_crypt_null_safe: ^3.0.0

  html: ^0.15.4
  crypto: ^3.0.5
  image_picker: ^1.1.2
  webview_flutter: ^4.9.0

  vocsy_epub_viewer: ^3.0.0
  hive: ^2.2.3

  # Payment
  flutterwave_standard:
    git:
      url: https://github.com/iqonic-design/flutterwave_standard.git
      ref: main
  razorpay_flutter: ^1.3.7

  flutter_localizations:
    sdk: flutter

  uuid: any
  path: any
dependency_overrides:
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # CODE GENERATION
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json_image/
    - assets/flag/
    - assets/epub/